# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sro.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'sro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import cstx_pb2 as cstx__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsro.proto\x12\x04\x65\x61sm\x1a\ncstx.proto\"\x18\n\x07Resolve:\r\x92\xb5\x18\t\n\x07resolve\"\x12\n\x04Open:\n\x92\xb5\x18\x06\n\x04open\"#\n\x0cHasSubdomain:\x13\x92\xb5\x18\x0f\n\rhas-subdomain\"\x18\n\x07\x43ontain:\r\x92\xb5\x18\t\n\x07\x63ontain\"\x14\n\x05Hosts:\x0b\x92\xb5\x18\x07\n\x05hosts\"\x12\n\x04Uses:\n\x92\xb5\x18\x06\n\x04uses\"\x16\n\x06Refers:\x0c\x92\xb5\x18\x08\n\x06refers\"\x1d\n\tSecuredBy:\x10\x92\xb5\x18\x0c\n\nsecured_by\"\x18\n\x07\x45xploit:\r\x92\xb5\x18\t\n\x07\x65xploit\"\x16\n\x06\x41\x66\x66\x65\x63t:\x0c\x92\xb5\x18\x08\n\x06\x61\x66\x66\x65\x63t\"\x16\n\x06Invest:\x0c\x92\xb5\x18\x08\n\x06invest\"\x10\n\x03Own:\t\x92\xb5\x18\x05\n\x03own\"\x1b\n\x08\x46iledFor:\x0f\x92\xb5\x18\x0b\n\tfiled-forB?Z=github.com/chainreactors/libcstx/go/proto/easmproto;easmprotob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/chainreactors/libcstx/go/proto/easmproto;easmproto'
  _globals['_RESOLVE']._loaded_options = None
  _globals['_RESOLVE']._serialized_options = b'\222\265\030\t\n\007resolve'
  _globals['_OPEN']._loaded_options = None
  _globals['_OPEN']._serialized_options = b'\222\265\030\006\n\004open'
  _globals['_HASSUBDOMAIN']._loaded_options = None
  _globals['_HASSUBDOMAIN']._serialized_options = b'\222\265\030\017\n\rhas-subdomain'
  _globals['_CONTAIN']._loaded_options = None
  _globals['_CONTAIN']._serialized_options = b'\222\265\030\t\n\007contain'
  _globals['_HOSTS']._loaded_options = None
  _globals['_HOSTS']._serialized_options = b'\222\265\030\007\n\005hosts'
  _globals['_USES']._loaded_options = None
  _globals['_USES']._serialized_options = b'\222\265\030\006\n\004uses'
  _globals['_REFERS']._loaded_options = None
  _globals['_REFERS']._serialized_options = b'\222\265\030\010\n\006refers'
  _globals['_SECUREDBY']._loaded_options = None
  _globals['_SECUREDBY']._serialized_options = b'\222\265\030\014\n\nsecured_by'
  _globals['_EXPLOIT']._loaded_options = None
  _globals['_EXPLOIT']._serialized_options = b'\222\265\030\t\n\007exploit'
  _globals['_AFFECT']._loaded_options = None
  _globals['_AFFECT']._serialized_options = b'\222\265\030\010\n\006affect'
  _globals['_INVEST']._loaded_options = None
  _globals['_INVEST']._serialized_options = b'\222\265\030\010\n\006invest'
  _globals['_OWN']._loaded_options = None
  _globals['_OWN']._serialized_options = b'\222\265\030\005\n\003own'
  _globals['_FILEDFOR']._loaded_options = None
  _globals['_FILEDFOR']._serialized_options = b'\222\265\030\013\n\tfiled-for'
  _globals['_RESOLVE']._serialized_start=31
  _globals['_RESOLVE']._serialized_end=55
  _globals['_OPEN']._serialized_start=57
  _globals['_OPEN']._serialized_end=75
  _globals['_HASSUBDOMAIN']._serialized_start=77
  _globals['_HASSUBDOMAIN']._serialized_end=112
  _globals['_CONTAIN']._serialized_start=114
  _globals['_CONTAIN']._serialized_end=138
  _globals['_HOSTS']._serialized_start=140
  _globals['_HOSTS']._serialized_end=160
  _globals['_USES']._serialized_start=162
  _globals['_USES']._serialized_end=180
  _globals['_REFERS']._serialized_start=182
  _globals['_REFERS']._serialized_end=204
  _globals['_SECUREDBY']._serialized_start=206
  _globals['_SECUREDBY']._serialized_end=235
  _globals['_EXPLOIT']._serialized_start=237
  _globals['_EXPLOIT']._serialized_end=261
  _globals['_AFFECT']._serialized_start=263
  _globals['_AFFECT']._serialized_end=285
  _globals['_INVEST']._serialized_start=287
  _globals['_INVEST']._serialized_end=309
  _globals['_OWN']._serialized_start=311
  _globals['_OWN']._serialized_end=327
  _globals['_FILEDFOR']._serialized_start=329
  _globals['_FILEDFOR']._serialized_end=356
# @@protoc_insertion_point(module_scope)
