# @generated by cstx-codegen — DO NOT EDIT MANUALLY

from typing import List, Optional, Union

from pydantic import BaseModel, Field, ConfigDict


class SCOBase(BaseModel):
    """Base model for all CSTX SCO node types."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    cstx_type: str
    cstx_id: str


class Domain(SCOBase):
    """Generated schema for 'domain' node type."""

    host: str


class Subdomain(SCOBase):
    """Generated schema for 'subdomain' node type."""

    host: str
    is_tld: bool = Field(default=False)
    ttl: int = Field(default=0)
    resolver: Optional[List[str]] = Field(default=None)
    a: Optional[List[str]] = Field(default=None)
    aaaa: Optional[List[str]] = Field(default=None)
    cname: Optional[List[str]] = Field(default=None)
    mx: Optional[List[str]] = Field(default=None)
    ns: Optional[List[str]] = Field(default=None)
    txt: Optional[List[str]] = Field(default=None)


class Ip(SCOBase):
    """Generated schema for 'ip' node type."""

    ip: str
    country: str = Field(default="")
    area: str = Field(default="")
    asn_number: str = Field(default="")
    as_name: str = Field(default="")
    cdn_name: str = Field(default="")
    cloud_name: str = Field(default="")
    waf_name: str = Field(default="")
    cdn: bool = Field(default=False)
    cloud: bool = Field(default=False)
    waf: bool = Field(default=False)


class Cidr(SCOBase):
    """Generated schema for 'cidr' node type."""

    cidr: str


class Port(SCOBase):
    """Generated schema for 'port' node type."""

    ip: str
    port: str
    protocol: str


class App(SCOBase):
    """Generated schema for 'app' node type."""

    app_id: str
    url: str = Field(default="")
    frameworks: Optional[List[str]] = Field(default=None)
    title: str = Field(default="")
    midware: str = Field(default="")
    status: str = Field(default="")
    status_code: int = Field(default=0)
    host: str = Field(default="")
    content_type: str = Field(default="")
    body_length: int = Field(default=0)
    header_length: int = Field(default=0)


class Url(SCOBase):
    """Generated schema for 'url' node type."""

    scheme: str
    host: str = Field(default="")
    port: str = Field(default="")
    path: str = Field(default="")
    ip: str = Field(default="")
    status_code: int = Field(default=0)
    title: str = Field(default="")
    body_length: int = Field(default=0)
    content_type: str = Field(default="")
    redirect_url: str = Field(default="")
    frameworks: Optional[List[str]] = Field(default=None)


class Framework(SCOBase):
    """Generated schema for 'framework' node type."""

    name: str
    part: str = Field(default="")
    vendor: str = Field(default="")
    product: str = Field(default="")
    version: str = Field(default="")
    tags: Optional[List[str]] = Field(default=None)
    is_focus: bool = Field(default=False)
    sources: Optional[List[str]] = Field(default=None)


class Vuln(SCOBase):
    """Generated schema for 'vuln' node type."""

    value: str
    vuln_id: str = Field(default="")
    name: str = Field(default="")
    asset_id: str = Field(default="")
    severity: str = Field(default="")
    tags: Optional[List[str]] = Field(default=None)
    ip: str = Field(default="")
    host: str = Field(default="")
    port: str = Field(default="")
    protocol: str = Field(default="")
    scheme: str = Field(default="")
    url: str = Field(default="")
    path: str = Field(default="")
    pocname: str = Field(default="")
    request: str = Field(default="")
    response: str = Field(default="")
    username: str = Field(default="")
    password: str = Field(default="")


class Certificate(SCOBase):
    """Generated schema for 'certificate' node type."""

    fingerprint: str
    serial: str = Field(default="")
    issuer: str = Field(default="")
    subject: str = Field(default="")
    not_before: str = Field(default="")
    not_after: str = Field(default="")
    san: Optional[List[str]] = Field(default=None)
    host: str = Field(default="")
    ip: str = Field(default="")


class Company(SCOBase):
    """Generated schema for 'company' node type."""

    name: str
    perc: str = Field(default="")
    tycid: str = Field(default="")
    icp: str = Field(default="")
    parent: str = Field(default="")


class Icp(SCOBase):
    """Generated schema for 'icp' node type."""

    icp: str
    sub: str = Field(default="")
    date: str = Field(default="")
    company: str = Field(default="")
    title: str = Field(default="")
    domain: str = Field(default="")
    ip: str = Field(default="")


class Bucket(SCOBase):
    """Generated schema for 'bucket' node type."""

    provider: str = Field(default="")
    name: str = Field(default="")
    region: str = Field(default="")
    endpoint: str
    acl: str = Field(default="")
    object_count: int = Field(default=0)
    known_paths: Optional[List[str]] = Field(default=None)
    source_url: str = Field(default="")


class Endpoint(SCOBase):
    """Generated schema for 'endpoint' node type."""

    url: str
    method: str = Field(default="")
    path: str = Field(default="")
    content_type: str = Field(default="")
    status_code: int = Field(default=0)
    source: str = Field(default="")
    source_url: str = Field(default="")
    parameters: Optional[List[str]] = Field(default=None)
    tags: Optional[List[str]] = Field(default=None)


class Host(SCOBase):
    """Generated schema for 'host' node type."""

    hostname: str
    local_ips: Optional[List[str]] = Field(default=None)
    gateway_ips: Optional[List[str]] = Field(default=None)
    dns_servers: Optional[List[str]] = Field(default=None)
    domain_name: str = Field(default="")
    domain_role: str = Field(default="")


class Repository(SCOBase):
    """Generated schema for 'repository' node type."""

    provider: str = Field(default="")
    name: str = Field(default="")
    url: str
    owner: str = Field(default="")
    description: str = Field(default="")
    stars: int = Field(default=0)
    is_fork: bool = Field(default=False)
    matched_dorks: Optional[List[str]] = Field(default=None)


class Secret(SCOBase):
    """Generated schema for 'secret' node type."""

    kind: str = Field(default="")
    detector: str = Field(default="")
    redacted: str = Field(default="")
    fingerprint: str
    source: str = Field(default="")
    source_url: str = Field(default="")
    file_path: str = Field(default="")
    line: int = Field(default=0)
    commit: str = Field(default="")
    verified: bool = Field(default=False)
    severity: str = Field(default="")


SCONode = Union[
    Domain,
    Subdomain,
    Ip,
    Cidr,
    Port,
    App,
    Url,
    Framework,
    Vuln,
    Certificate,
    Company,
    Icp,
    Bucket,
    Endpoint,
    Host,
    Repository,
    Secret,
]

SCO_TYPE_MAP: dict[str, type[SCOBase]] = {
    "domain": Domain,
    "subdomain": Subdomain,
    "ip": Ip,
    "cidr": Cidr,
    "port": Port,
    "app": App,
    "url": Url,
    "framework": Framework,
    "vuln": Vuln,
    "certificate": Certificate,
    "company": Company,
    "icp": Icp,
    "bucket": Bucket,
    "endpoint": Endpoint,
    "host": Host,
    "repository": Repository,
    "secret": Secret,
}


def parse_sco_node(data: dict) -> SCOBase:
    """Parse a raw dict into the appropriate typed SCO model.

    Dispatches on the 'cstx_type' field to select the correct class.
    Raises KeyError if cstx_type is missing or unknown.
    """
    cstx_type = data.get("cstx_type")
    if cstx_type is None:
        raise KeyError("Missing 'cstx_type' field in data")
    cls = SCO_TYPE_MAP.get(cstx_type)
    if cls is None:
        raise KeyError(f"Unknown cstx_type: {cstx_type!r}")
    return cls.model_validate(data)


__all__ = [
    "SCOBase",
    "Domain",
    "Subdomain",
    "Ip",
    "Cidr",
    "Port",
    "App",
    "Url",
    "Framework",
    "Vuln",
    "Certificate",
    "Company",
    "Icp",
    "Bucket",
    "Endpoint",
    "Host",
    "Repository",
    "Secret",
    "SCONode",
    "SCO_TYPE_MAP",
    "parse_sco_node",
]
