# @generated by cstx-codegen — DO NOT EDIT MANUALLY

from typing import List, Literal

from pydantic import BaseModel, ConfigDict


RelationType = Literal["resolve", "open", "secured_by", "invest", "own", "filed-for"]

RELATION_TYPES: List[str] = ["resolve", "open", "secured_by", "invest", "own", "filed-for"]


class SROBase(BaseModel):
    """Base model for all CSTX SRO (relationship) types."""

    model_config = ConfigDict(extra="allow")

    source_id: str
    target_id: str
    relation_type: RelationType
    sources: List[str]


__all__ = [
    "RelationType",
    "RELATION_TYPES",
    "SROBase",
]
