// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v6.33.0
// source: sro.proto

package easmproto

import (
	_ "github.com/chainreactors/libcstx/go/proto/cstxproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resolve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Resolve) Reset() {
	*x = Resolve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resolve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolve) ProtoMessage() {}

func (x *Resolve) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolve.ProtoReflect.Descriptor instead.
func (*Resolve) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{0}
}

type Open struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Open) Reset() {
	*x = Open{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open) ProtoMessage() {}

func (x *Open) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open.ProtoReflect.Descriptor instead.
func (*Open) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{1}
}

type HasSubdomain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HasSubdomain) Reset() {
	*x = HasSubdomain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasSubdomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSubdomain) ProtoMessage() {}

func (x *HasSubdomain) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSubdomain.ProtoReflect.Descriptor instead.
func (*HasSubdomain) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{2}
}

type Contain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Contain) Reset() {
	*x = Contain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contain) ProtoMessage() {}

func (x *Contain) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contain.ProtoReflect.Descriptor instead.
func (*Contain) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{3}
}

type Hosts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Hosts) Reset() {
	*x = Hosts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hosts) ProtoMessage() {}

func (x *Hosts) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hosts.ProtoReflect.Descriptor instead.
func (*Hosts) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{4}
}

type Uses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Uses) Reset() {
	*x = Uses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uses) ProtoMessage() {}

func (x *Uses) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uses.ProtoReflect.Descriptor instead.
func (*Uses) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{5}
}

type Refers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Refers) Reset() {
	*x = Refers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Refers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refers) ProtoMessage() {}

func (x *Refers) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refers.ProtoReflect.Descriptor instead.
func (*Refers) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{6}
}

type SecuredBy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SecuredBy) Reset() {
	*x = SecuredBy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecuredBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecuredBy) ProtoMessage() {}

func (x *SecuredBy) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecuredBy.ProtoReflect.Descriptor instead.
func (*SecuredBy) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{7}
}

type Exploit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Exploit) Reset() {
	*x = Exploit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exploit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exploit) ProtoMessage() {}

func (x *Exploit) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exploit.ProtoReflect.Descriptor instead.
func (*Exploit) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{8}
}

type Affect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Affect) Reset() {
	*x = Affect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Affect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Affect) ProtoMessage() {}

func (x *Affect) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Affect.ProtoReflect.Descriptor instead.
func (*Affect) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{9}
}

type Invest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Invest) Reset() {
	*x = Invest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Invest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invest) ProtoMessage() {}

func (x *Invest) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invest.ProtoReflect.Descriptor instead.
func (*Invest) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{10}
}

type Own struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Own) Reset() {
	*x = Own{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Own) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Own) ProtoMessage() {}

func (x *Own) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Own.ProtoReflect.Descriptor instead.
func (*Own) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{11}
}

type FiledFor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FiledFor) Reset() {
	*x = FiledFor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sro_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FiledFor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiledFor) ProtoMessage() {}

func (x *FiledFor) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiledFor.ProtoReflect.Descriptor instead.
func (*FiledFor) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{12}
}

var File_sro_proto protoreflect.FileDescriptor

var file_sro_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x65, 0x61, 0x73,
	0x6d, 0x1a, 0x0a, 0x63, 0x73, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a,
	0x07, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x3a, 0x0d, 0x92, 0xb5, 0x18, 0x09, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x22, 0x12, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x3a,
	0x0a, 0x92, 0xb5, 0x18, 0x06, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x22, 0x23, 0x0a, 0x0c, 0x48,
	0x61, 0x73, 0x53, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x3a, 0x13, 0x92, 0xb5, 0x18,
	0x0f, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x2d, 0x73, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x22, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x3a, 0x0d, 0x92, 0xb5, 0x18,
	0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x22, 0x14, 0x0a, 0x05, 0x48, 0x6f,
	0x73, 0x74, 0x73, 0x3a, 0x0b, 0x92, 0xb5, 0x18, 0x07, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73,
	0x22, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x73, 0x3a, 0x0a, 0x92, 0xb5, 0x18, 0x06, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x73, 0x22, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x66, 0x65, 0x72, 0x73, 0x3a, 0x0c,
	0x92, 0xb5, 0x18, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x65, 0x72, 0x73, 0x22, 0x1d, 0x0a, 0x09,
	0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x64, 0x42, 0x79, 0x3a, 0x10, 0x92, 0xb5, 0x18, 0x0c, 0x0a,
	0x0a, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x22, 0x18, 0x0a, 0x07, 0x45,
	0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x3a, 0x0d, 0x92, 0xb5, 0x18, 0x09, 0x0a, 0x07, 0x65, 0x78,
	0x70, 0x6c, 0x6f, 0x69, 0x74, 0x22, 0x16, 0x0a, 0x06, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x3a,
	0x0c, 0x92, 0xb5, 0x18, 0x08, 0x0a, 0x06, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x22, 0x16, 0x0a,
	0x06, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x3a, 0x0c, 0x92, 0xb5, 0x18, 0x08, 0x0a, 0x06, 0x69,
	0x6e, 0x76, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x03, 0x4f, 0x77, 0x6e, 0x3a, 0x09, 0x92, 0xb5,
	0x18, 0x05, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x22, 0x1b, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x64,
	0x46, 0x6f, 0x72, 0x3a, 0x0f, 0x92, 0xb5, 0x18, 0x0b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x64,
	0x2d, 0x66, 0x6f, 0x72, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x2f, 0x6c, 0x69, 0x62, 0x63, 0x73, 0x74, 0x78, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x65, 0x61, 0x73, 0x6d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x65, 0x61, 0x73, 0x6d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sro_proto_rawDescOnce sync.Once
	file_sro_proto_rawDescData = file_sro_proto_rawDesc
)

func file_sro_proto_rawDescGZIP() []byte {
	file_sro_proto_rawDescOnce.Do(func() {
		file_sro_proto_rawDescData = protoimpl.X.CompressGZIP(file_sro_proto_rawDescData)
	})
	return file_sro_proto_rawDescData
}

var file_sro_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_sro_proto_goTypes = []interface{}{
	(*Resolve)(nil),      // 0: easm.Resolve
	(*Open)(nil),         // 1: easm.Open
	(*HasSubdomain)(nil), // 2: easm.HasSubdomain
	(*Contain)(nil),      // 3: easm.Contain
	(*Hosts)(nil),        // 4: easm.Hosts
	(*Uses)(nil),         // 5: easm.Uses
	(*Refers)(nil),       // 6: easm.Refers
	(*SecuredBy)(nil),    // 7: easm.SecuredBy
	(*Exploit)(nil),      // 8: easm.Exploit
	(*Affect)(nil),       // 9: easm.Affect
	(*Invest)(nil),       // 10: easm.Invest
	(*Own)(nil),          // 11: easm.Own
	(*FiledFor)(nil),     // 12: easm.FiledFor
}
var file_sro_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sro_proto_init() }
func file_sro_proto_init() {
	if File_sro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sro_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resolve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Open); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasSubdomain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hosts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Refers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecuredBy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exploit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Affect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Invest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Own); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sro_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FiledFor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sro_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sro_proto_goTypes,
		DependencyIndexes: file_sro_proto_depIdxs,
		MessageInfos:      file_sro_proto_msgTypes,
	}.Build()
	File_sro_proto = out.File
	file_sro_proto_rawDesc = nil
	file_sro_proto_goTypes = nil
	file_sro_proto_depIdxs = nil
}
