# @generated by cstx-codegen — DO NOT EDIT MANUALLY

# Schema-only shapes: the high-level cstx SDK mixes in its runtime
# model base (Element/SCO) at the wrapper layer. This module must stay
# free of cstx imports so cstxpy never depends on the high-level package.

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, ConfigDict

class DomainBase(BaseModel):
    """Generated schema for 'domain' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    host: str

class SubdomainBase(BaseModel):
    """Generated schema for 'subdomain' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    host: str
    is_tld: bool = Field(default=False)
    ttl: int = Field(default=0)
    resolver: Optional[List[str]] = Field(default=None)
    a: Optional[List[str]] = Field(default=None)
    aaaa: Optional[List[str]] = Field(default=None)
    cname: Optional[List[str]] = Field(default=None)
    mx: Optional[List[str]] = Field(default=None)
    ns: Optional[List[str]] = Field(default=None)
    txt: Optional[List[str]] = Field(default=None)

class IpBase(BaseModel):
    """Generated schema for 'ip' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    ip: str
    country: str = Field(default="")
    area: str = Field(default="")
    asn_number: str = Field(default="")
    as_name: str = Field(default="")
    cdn_name: str = Field(default="")
    cloud_name: str = Field(default="")
    waf_name: str = Field(default="")
    cdn: bool = Field(default=False)
    cloud: bool = Field(default=False)
    waf: bool = Field(default=False)

class CidrBase(BaseModel):
    """Generated schema for 'cidr' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    cidr: str

class PortBase(BaseModel):
    """Generated schema for 'port' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    ip: str
    port: str
    protocol: str

class AppBase(BaseModel):
    """Generated schema for 'app' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    app_id: str
    url: str = Field(default="")
    frameworks: Optional[List[str]] = Field(default=None)
    title: str = Field(default="")
    midware: str = Field(default="")
    status: str = Field(default="")
    status_code: int = Field(default=0)
    host: str = Field(default="")
    content_type: str = Field(default="")
    body_length: int = Field(default=0)
    header_length: int = Field(default=0)
    screenshot_id: str = Field(default="")
    screenshot_path: str = Field(default="")
    ip: str = Field(default="")
    port: str = Field(default="")

class UrlBase(BaseModel):
    """Generated schema for 'url' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    scheme: str
    host: str = Field(default="")
    port: str = Field(default="")
    path: str = Field(default="")
    ip: str = Field(default="")
    status_code: int = Field(default=0)
    title: str = Field(default="")
    body_length: int = Field(default=0)
    content_type: str = Field(default="")
    redirect_url: str = Field(default="")
    frameworks: Optional[List[str]] = Field(default=None)

class FrameworkBase(BaseModel):
    """Generated schema for 'framework' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    name: str
    part: str = Field(default="")
    vendor: str = Field(default="")
    product: str = Field(default="")
    version: str = Field(default="")
    tags: Optional[List[str]] = Field(default=None)
    is_focus: bool = Field(default=False)
    sources: Optional[List[str]] = Field(default=None)

class VulnBase(BaseModel):
    """Generated schema for 'vuln' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    value: str
    vuln_id: str = Field(default="")
    name: str = Field(default="")
    asset_id: str = Field(default="")
    severity: str = Field(default="")
    tags: Optional[List[str]] = Field(default=None)
    ip: str = Field(default="")
    host: str = Field(default="")
    port: str = Field(default="")
    protocol: str = Field(default="")
    scheme: str = Field(default="")
    url: str = Field(default="")
    path: str = Field(default="")
    pocname: str = Field(default="")
    request: str = Field(default="")
    response: str = Field(default="")
    username: str = Field(default="")
    password: str = Field(default="")
    matched: bool = Field(default=False)
    extracted: bool = Field(default=False)

class SarifVulnBase(BaseModel):
    """Generated schema for 'sarif_vuln' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    value: str
    vuln_id: str = Field(default="")
    title: str = Field(default="")
    description: str = Field(default="")
    source: str = Field(default="")
    target: str = Field(default="")
    tags: Optional[List[str]] = Field(default=None)
    asset_cstx_id: str = Field(default="")
    kind: str = Field(default="")
    level: str = Field(default="")
    baseline_state: str = Field(default="")
    rule_id: str = Field(default="")
    evidence: str = Field(default="")

class CertificateBase(BaseModel):
    """Generated schema for 'certificate' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    fingerprint: str
    serial: str = Field(default="")
    issuer: str = Field(default="")
    subject: str = Field(default="")
    not_before: str = Field(default="")
    not_after: str = Field(default="")
    san: Optional[List[str]] = Field(default=None)
    host: str = Field(default="")
    ip: str = Field(default="")

class CompanyBase(BaseModel):
    """Generated schema for 'company' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    name: str
    perc: str = Field(default="")
    tycid: str = Field(default="")
    icp: str = Field(default="")
    parent: str = Field(default="")

class IcpBase(BaseModel):
    """Generated schema for 'icp' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    icp: str
    sub: str = Field(default="")
    date: str = Field(default="")
    company: str = Field(default="")
    title: str = Field(default="")
    domain: str = Field(default="")
    ip: str = Field(default="")

class BucketBase(BaseModel):
    """Generated schema for 'bucket' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    provider: str = Field(default="")
    name: str = Field(default="")
    region: str = Field(default="")
    endpoint: str
    acl: str = Field(default="")
    object_count: int = Field(default=0)
    known_paths: Optional[List[str]] = Field(default=None)
    source_url: str = Field(default="")

class EndpointBase(BaseModel):
    """Generated schema for 'endpoint' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    url: str
    method: str = Field(default="")
    path: str = Field(default="")
    content_type: str = Field(default="")
    status_code: int = Field(default=0)
    source: str = Field(default="")
    source_url: str = Field(default="")
    parameters: Optional[List[str]] = Field(default=None)
    tags: Optional[List[str]] = Field(default=None)

class HostBase(BaseModel):
    """Generated schema for 'host' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    hostname: str
    local_ips: Optional[List[str]] = Field(default=None)
    gateway_ips: Optional[List[str]] = Field(default=None)
    dns_servers: Optional[List[str]] = Field(default=None)
    domain_name: str = Field(default="")
    domain_role: str = Field(default="")

class RepositoryBase(BaseModel):
    """Generated schema for 'repository' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    provider: str = Field(default="")
    name: str = Field(default="")
    url: str
    owner: str = Field(default="")
    description: str = Field(default="")
    stars: int = Field(default=0)
    is_fork: bool = Field(default=False)
    matched_dorks: Optional[List[str]] = Field(default=None)

class SecretBase(BaseModel):
    """Generated schema for 'secret' node type."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)

    kind: str = Field(default="")
    detector: str = Field(default="")
    redacted: str = Field(default="")
    fingerprint: str
    source: str = Field(default="")
    source_url: str = Field(default="")
    file_path: str = Field(default="")
    line: int = Field(default=0)
    commit: str = Field(default="")
    verified: bool = Field(default=False)
    severity: str = Field(default="")

__all__ = [
    "DomainBase",
    "SubdomainBase",
    "IpBase",
    "CidrBase",
    "PortBase",
    "AppBase",
    "UrlBase",
    "FrameworkBase",
    "VulnBase",
    "SarifVulnBase",
    "CertificateBase",
    "CompanyBase",
    "IcpBase",
    "BucketBase",
    "EndpointBase",
    "HostBase",
    "RepositoryBase",
    "SecretBase",
]
