# @generated by cstx-codegen — DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List, Literal, Optional

RelationType = Literal["resolve", "open", "has-subdomain", "contain", "hosts", "uses", "refers", "secured_by", "exploit", "affect", "invest", "own", "filed-for"]

RELATION_TYPES: List[RelationType] = ["resolve", "open", "has-subdomain", "contain", "hosts", "uses", "refers", "secured_by", "exploit", "affect", "invest", "own", "filed-for"]
