[package]
name = "cstxpy"
version.workspace = true
edition.workspace = true
workspace = "../../cstx-core"

[lib]
name = "_cstxpy"
crate-type = ["cdylib"]

[dependencies]
cstx-core = { path = "../../cstx-core/crates/cstx-core", default-features = false, features = ["python"] }
pyo3 = { workspace = true, features = ["extension-module", "abi3-py310", "generate-import-lib"] }

[lints]
workspace = true
