// @generated by cstx-codegen — DO NOT EDIT MANUALLY

export interface SCOBase {
  cstx_type: string;
  cstx_id: string;
}

export interface Domain extends SCOBase {
  host: string;
}

export interface Subdomain extends SCOBase {
  host: string;
  is_tld?: boolean;
  ttl?: number;
  resolver?: string[];
  a?: string[];
  aaaa?: string[];
  cname?: string[];
  mx?: string[];
  ns?: string[];
  txt?: string[];
}

export interface Ip extends SCOBase {
  ip: string;
  country?: string;
  area?: string;
  asn_number?: string;
  as_name?: string;
  cdn_name?: string;
  cloud_name?: string;
  waf_name?: string;
  cdn?: boolean;
  cloud?: boolean;
  waf?: boolean;
}

export interface Cidr extends SCOBase {
  cidr: string;
}

export interface Port extends SCOBase {
  ip: string;
  port: string;
  protocol: string;
}

export interface App extends SCOBase {
  app_id: string;
  url?: string;
  frameworks?: string[];
  title?: string;
  midware?: string;
  status?: string;
  status_code?: number;
  host?: string;
  content_type?: string;
  body_length?: number;
  header_length?: number;
}

export interface Url extends SCOBase {
  scheme: string;
  host?: string;
  port?: string;
  path?: string;
  ip?: string;
  status_code?: number;
  title?: string;
  body_length?: number;
  content_type?: string;
  redirect_url?: string;
  frameworks?: string[];
}

export interface Framework extends SCOBase {
  name: string;
  part?: string;
  vendor?: string;
  product?: string;
  version?: string;
  tags?: string[];
  is_focus?: boolean;
  sources?: string[];
}

export interface Vuln extends SCOBase {
  value: string;
  vuln_id?: string;
  name?: string;
  asset_id?: string;
  severity?: string;
  tags?: string[];
  ip?: string;
  host?: string;
  port?: string;
  protocol?: string;
  scheme?: string;
  url?: string;
  path?: string;
  pocname?: string;
  request?: string;
  response?: string;
  username?: string;
  password?: string;
}

export interface Certificate extends SCOBase {
  fingerprint: string;
  serial?: string;
  issuer?: string;
  subject?: string;
  not_before?: string;
  not_after?: string;
  san?: string[];
  host?: string;
  ip?: string;
}

export interface Company extends SCOBase {
  name: string;
  perc?: string;
  tycid?: string;
  icp?: string;
  parent?: string;
}

export interface Icp extends SCOBase {
  icp: string;
  sub?: string;
  date?: string;
  company?: string;
  title?: string;
  domain?: string;
  ip?: string;
}

export interface Bucket extends SCOBase {
  provider?: string;
  name?: string;
  region?: string;
  endpoint: string;
  acl?: string;
  object_count?: number;
  known_paths?: string[];
  source_url?: string;
}

export interface Endpoint extends SCOBase {
  url: string;
  method?: string;
  path?: string;
  content_type?: string;
  status_code?: number;
  source?: string;
  source_url?: string;
  parameters?: string[];
  tags?: string[];
}

export interface Host extends SCOBase {
  hostname: string;
  local_ips?: string[];
  gateway_ips?: string[];
  dns_servers?: string[];
  domain_name?: string;
  domain_role?: string;
}

export interface Repository extends SCOBase {
  provider?: string;
  name?: string;
  url: string;
  owner?: string;
  description?: string;
  stars?: number;
  is_fork?: boolean;
  matched_dorks?: string[];
}

export interface Secret extends SCOBase {
  kind?: string;
  detector?: string;
  redacted?: string;
  fingerprint: string;
  source?: string;
  source_url?: string;
  file_path?: string;
  line?: number;
  commit?: string;
  verified?: boolean;
  severity?: string;
}

export type SCONode =
  Domain |
  Subdomain |
  Ip |
  Cidr |
  Port |
  App |
  Url |
  Framework |
  Vuln |
  Certificate |
  Company |
  Icp |
  Bucket |
  Endpoint |
  Host |
  Repository |
  Secret;

export const SCO_TYPE_MAP: Record<string, string> = {
  "domain": "Domain",
  "subdomain": "Subdomain",
  "ip": "Ip",
  "cidr": "Cidr",
  "port": "Port",
  "app": "App",
  "url": "Url",
  "framework": "Framework",
  "vuln": "Vuln",
  "certificate": "Certificate",
  "company": "Company",
  "icp": "Icp",
  "bucket": "Bucket",
  "endpoint": "Endpoint",
  "host": "Host",
  "repository": "Repository",
  "secret": "Secret",
};
