// @generated by cstx-codegen — DO NOT EDIT MANUALLY

export type RelationType = "resolve" | "open" | "secured_by" | "invest" | "own" | "filed-for";

export const RELATION_TYPES = ["resolve", "open", "secured_by", "invest", "own", "filed-for"] as const;

export interface SROBase {
  source_id: string;
  target_id: string;
  relation_type: RelationType;
  sources: string[];
}
