/* Generated by cbindgen — do not edit */

#ifndef CSTX_FFI_H
#define CSTX_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

enum CstxStatusCode
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  Ok = 0,
  InvalidArgument = 1,
  NotFound = 2,
  Conflict = 3,
  NotInitialized = 4,
  Unsupported = 5,
  Internal = 6,
  Validation = 7,
  Parse = 8,
  Io = 9,
  CorruptData = 10,
  CursorInvalidated = 11,
};
#if __STDC_VERSION__ >= 202311L
typedef enum CstxStatusCode CstxStatusCode;
#else
typedef int32_t CstxStatusCode;
#endif // __STDC_VERSION__ >= 202311L

typedef struct CstxEdgeIterator CstxEdgeIterator;

typedef struct CstxHandle CstxHandle;

typedef struct CstxNodeIterator CstxNodeIterator;

typedef struct CstxBuffer {
  uint8_t *data;
  uintptr_t len;
} CstxBuffer;

typedef struct CstxSlice {
  const uint8_t *data;
  uintptr_t len;
} CstxSlice;

/**
 * Release a Rust-owned output or error buffer.
 */
void cstx_buffer_free(struct CstxBuffer *buffer);

CstxStatusCode cstx_open(struct CstxSlice config_json,
                         struct CstxHandle **output,
                         struct CstxBuffer *error);

void cstx_close(struct CstxHandle *handle);

void cstx_free(struct CstxHandle *handle);

CstxStatusCode cstx_last_change_json(struct CstxHandle *handle,
                                     struct CstxBuffer *output,
                                     struct CstxBuffer *error);

CstxStatusCode cstx_schema_register(struct CstxHandle *handle,
                                    struct CstxSlice node_type,
                                    struct CstxSlice schema_json,
                                    struct CstxSlice value_field,
                                    struct CstxBuffer *error);

CstxStatusCode cstx_schema_contains(struct CstxHandle *handle,
                                    struct CstxSlice node_type,
                                    uint8_t *output,
                                    struct CstxBuffer *error);

CstxStatusCode cstx_schema_get_json(struct CstxHandle *handle,
                                    struct CstxSlice node_type,
                                    struct CstxBuffer *output,
                                    struct CstxBuffer *error);

CstxStatusCode cstx_schema_load_plugin(struct CstxHandle *handle,
                                       struct CstxSlice name,
                                       struct CstxBuffer *error);

CstxStatusCode cstx_schema_load_all_plugins(struct CstxHandle *handle, struct CstxBuffer *error);

CstxStatusCode cstx_schema_available_plugins_json(struct CstxHandle *handle,
                                                  struct CstxBuffer *output,
                                                  struct CstxBuffer *error);

CstxStatusCode cstx_graph_ingest(struct CstxHandle *handle,
                                 struct CstxSlice source,
                                 struct CstxSlice data,
                                 uint64_t *affected,
                                 struct CstxBuffer *error);

CstxStatusCode cstx_graph_node(struct CstxHandle *handle,
                               struct CstxSlice node_id,
                               struct CstxBuffer *output,
                               struct CstxBuffer *error);

CstxStatusCode cstx_graph_contains(struct CstxHandle *handle,
                                   struct CstxSlice node_id,
                                   uint8_t *output,
                                   struct CstxBuffer *error);

CstxStatusCode cstx_graph_stats(struct CstxHandle *handle,
                                struct CstxBuffer *output,
                                struct CstxBuffer *error);

CstxStatusCode cstx_graph_nodes(struct CstxHandle *handle,
                                struct CstxSlice filter_json,
                                struct CstxSlice options_json,
                                struct CstxNodeIterator **output,
                                struct CstxBuffer *error);

CstxStatusCode cstx_graph_edges(struct CstxHandle *handle,
                                struct CstxSlice filter_json,
                                struct CstxSlice options_json,
                                struct CstxEdgeIterator **output,
                                struct CstxBuffer *error);

CstxStatusCode cstx_graph_neighbors(struct CstxHandle *handle,
                                    struct CstxSlice node_id,
                                    struct CstxSlice direction,
                                    struct CstxSlice options_json,
                                    struct CstxNodeIterator **output,
                                    struct CstxBuffer *error);

CstxStatusCode cstx_graph_query(struct CstxHandle *handle,
                                struct CstxSlice expression,
                                struct CstxSlice options_json,
                                struct CstxNodeIterator **output,
                                struct CstxBuffer *error);

CstxStatusCode cstx_repo_commit(struct CstxHandle *handle,
                                struct CstxSlice ref_name,
                                struct CstxSlice message,
                                struct CstxSlice metadata_json,
                                struct CstxBuffer *output,
                                struct CstxBuffer *error);

CstxStatusCode cstx_repo_diff(struct CstxHandle *handle,
                              struct CstxSlice base_ref,
                              struct CstxSlice head_ref,
                              struct CstxBuffer *output,
                              struct CstxBuffer *error);

CstxStatusCode cstx_repo_dump(struct CstxHandle *handle,
                              struct CstxSlice compression,
                              struct CstxBuffer *output,
                              struct CstxBuffer *error);

CstxStatusCode cstx_repo_load(struct CstxHandle *handle,
                              struct CstxSlice data,
                              struct CstxSlice compression,
                              uint64_t *consumed,
                              struct CstxBuffer *error);

CstxStatusCode cstx_repo_dump_json(struct CstxHandle *handle,
                                   struct CstxBuffer *output,
                                   struct CstxBuffer *error);

CstxStatusCode cstx_repo_load_json(struct CstxHandle *handle,
                                   struct CstxSlice data,
                                   uint64_t *consumed,
                                   struct CstxBuffer *error);

CstxStatusCode cstx_repo_snapshot_fingerprint(struct CstxHandle *handle,
                                              struct CstxBuffer *output,
                                              struct CstxBuffer *error);

CstxStatusCode cstx_repo_head(struct CstxHandle *handle,
                              struct CstxSlice ref_name,
                              struct CstxBuffer *output,
                              struct CstxBuffer *error);

CstxStatusCode cstx_repo_refs(struct CstxHandle *handle,
                              struct CstxBuffer *output,
                              struct CstxBuffer *error);

#endif  /* CSTX_FFI_H */
