// @generated by cstx-codegen — DO NOT EDIT MANUALLY

package easm

import (
	"encoding/json"
	"fmt"

	"github.com/chainreactors/libcstx/go/proto/cstxproto"
)

// Node is one graph node as this extension's schema declares it.
//
// The payload crosses the boundary as an EntityValue: field names from the
// schema document, each value in the branch its column declares. Nothing here
// carries a field number, which is what lets a type declared at runtime travel
// the same way with no generated code at all.
type Node interface {
	CstxType() string
	EntityValue() (*cstxproto.EntityValue, error)
}

// Domain is the "domain" node type.
type Domain struct {
	Host  string         // host
	Extra map[string]any // extra
}

func (d Domain) CstxType() string { return "domain" }

// EntityValue encodes Domain as the schema-named payload.
func (d Domain) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 2)
	if len(d.Extra) > 0 {
		encoded, err := json.Marshal(d.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "host", Value: &cstxproto.EntityField_Text{Text: d.Host}})
	return &cstxproto.EntityValue{NodeType: "domain", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (d Domain) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := d.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// DomainFrom reads one payload back into Domain. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func DomainFrom(value *cstxproto.EntityValue) (Domain, error) {
	var out Domain
	if got := value.GetNodeType(); got != "domain" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "domain", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "host":
			out.Host = field.GetText()
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Subdomain is the "subdomain" node type.
type Subdomain struct {
	Host       string         // host
	IsTld      *bool          // is_tld
	Ttl        *int64         // ttl
	Resolver   []string       // resolver
	A          []string       // a
	Aaaa       []string       // aaaa
	Cname      []string       // cname
	Mx         []string       // mx
	Ns         []string       // ns
	Txt        []string       // txt
	Extra      map[string]any // extra
	RootDomain *string        // root_domain
}

func (s Subdomain) CstxType() string { return "subdomain" }

// EntityValue encodes Subdomain as the schema-named payload.
func (s Subdomain) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 12)
	if len(s.A) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "a", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: s.A}}})
	}
	if len(s.Aaaa) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "aaaa", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: s.Aaaa}}})
	}
	if len(s.Cname) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "cname", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: s.Cname}}})
	}
	if len(s.Extra) > 0 {
		encoded, err := json.Marshal(s.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "host", Value: &cstxproto.EntityField_Text{Text: s.Host}})
	if s.IsTld != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "is_tld", Value: &cstxproto.EntityField_Flag{Flag: *s.IsTld}})
	}
	if len(s.Mx) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "mx", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: s.Mx}}})
	}
	if len(s.Ns) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "ns", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: s.Ns}}})
	}
	if len(s.Resolver) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "resolver", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: s.Resolver}}})
	}
	if s.RootDomain != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "root_domain", Value: &cstxproto.EntityField_Text{Text: *s.RootDomain}})
	}
	if s.Ttl != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "ttl", Value: &cstxproto.EntityField_Number{Number: *s.Ttl}})
	}
	if len(s.Txt) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "txt", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: s.Txt}}})
	}
	return &cstxproto.EntityValue{NodeType: "subdomain", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (s Subdomain) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := s.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// SubdomainFrom reads one payload back into Subdomain. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func SubdomainFrom(value *cstxproto.EntityValue) (Subdomain, error) {
	var out Subdomain
	if got := value.GetNodeType(); got != "subdomain" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "subdomain", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "host":
			out.Host = field.GetText()
		case "is_tld":
			carried := field.GetFlag()
			out.IsTld = &carried
		case "ttl":
			carried := field.GetNumber()
			out.Ttl = &carried
		case "resolver":
			out.Resolver = field.GetList().GetValues()
		case "a":
			out.A = field.GetList().GetValues()
		case "aaaa":
			out.Aaaa = field.GetList().GetValues()
		case "cname":
			out.Cname = field.GetList().GetValues()
		case "mx":
			out.Mx = field.GetList().GetValues()
		case "ns":
			out.Ns = field.GetList().GetValues()
		case "txt":
			out.Txt = field.GetList().GetValues()
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		case "root_domain":
			carried := field.GetText()
			out.RootDomain = &carried
		}
	}
	return out, nil
}

// Ip is the "ip" node type.
type Ip struct {
	Ip        string         // ip
	Country   *string        // country
	Area      *string        // area
	AsnNumber *string        // asn_number
	AsName    *string        // as_name
	CdnName   *string        // cdn_name
	CloudName *string        // cloud_name
	WafName   *string        // waf_name
	Cdn       *bool          // cdn
	Cloud     *bool          // cloud
	Waf       *bool          // waf
	Extra     map[string]any // extra
	Cidr      *string        // cidr
}

func (i Ip) CstxType() string { return "ip" }

// EntityValue encodes Ip as the schema-named payload.
func (i Ip) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 13)
	if i.Area != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "area", Value: &cstxproto.EntityField_Text{Text: *i.Area}})
	}
	if i.AsName != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "as_name", Value: &cstxproto.EntityField_Text{Text: *i.AsName}})
	}
	if i.AsnNumber != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "asn_number", Value: &cstxproto.EntityField_Text{Text: *i.AsnNumber}})
	}
	if i.Cdn != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "cdn", Value: &cstxproto.EntityField_Flag{Flag: *i.Cdn}})
	}
	if i.CdnName != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "cdn_name", Value: &cstxproto.EntityField_Text{Text: *i.CdnName}})
	}
	if i.Cidr != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "cidr", Value: &cstxproto.EntityField_Text{Text: *i.Cidr}})
	}
	if i.Cloud != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "cloud", Value: &cstxproto.EntityField_Flag{Flag: *i.Cloud}})
	}
	if i.CloudName != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "cloud_name", Value: &cstxproto.EntityField_Text{Text: *i.CloudName}})
	}
	if i.Country != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "country", Value: &cstxproto.EntityField_Text{Text: *i.Country}})
	}
	if len(i.Extra) > 0 {
		encoded, err := json.Marshal(i.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "ip", Value: &cstxproto.EntityField_Text{Text: i.Ip}})
	if i.Waf != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "waf", Value: &cstxproto.EntityField_Flag{Flag: *i.Waf}})
	}
	if i.WafName != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "waf_name", Value: &cstxproto.EntityField_Text{Text: *i.WafName}})
	}
	return &cstxproto.EntityValue{NodeType: "ip", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (i Ip) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := i.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// IpFrom reads one payload back into Ip. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func IpFrom(value *cstxproto.EntityValue) (Ip, error) {
	var out Ip
	if got := value.GetNodeType(); got != "ip" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "ip", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "ip":
			out.Ip = field.GetText()
		case "country":
			carried := field.GetText()
			out.Country = &carried
		case "area":
			carried := field.GetText()
			out.Area = &carried
		case "asn_number":
			carried := field.GetText()
			out.AsnNumber = &carried
		case "as_name":
			carried := field.GetText()
			out.AsName = &carried
		case "cdn_name":
			carried := field.GetText()
			out.CdnName = &carried
		case "cloud_name":
			carried := field.GetText()
			out.CloudName = &carried
		case "waf_name":
			carried := field.GetText()
			out.WafName = &carried
		case "cdn":
			carried := field.GetFlag()
			out.Cdn = &carried
		case "cloud":
			carried := field.GetFlag()
			out.Cloud = &carried
		case "waf":
			carried := field.GetFlag()
			out.Waf = &carried
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		case "cidr":
			carried := field.GetText()
			out.Cidr = &carried
		}
	}
	return out, nil
}

// Cidr is the "cidr" node type.
type Cidr struct {
	Cidr  string         // cidr
	Extra map[string]any // extra
}

func (c Cidr) CstxType() string { return "cidr" }

// EntityValue encodes Cidr as the schema-named payload.
func (c Cidr) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 2)
	fields = append(fields, &cstxproto.EntityField{Name: "cidr", Value: &cstxproto.EntityField_Text{Text: c.Cidr}})
	if len(c.Extra) > 0 {
		encoded, err := json.Marshal(c.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	return &cstxproto.EntityValue{NodeType: "cidr", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (c Cidr) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := c.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// CidrFrom reads one payload back into Cidr. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func CidrFrom(value *cstxproto.EntityValue) (Cidr, error) {
	var out Cidr
	if got := value.GetNodeType(); got != "cidr" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "cidr", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "cidr":
			out.Cidr = field.GetText()
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Port is the "port" node type.
type Port struct {
	Ip       string         // ip
	Port     string         // port
	Protocol string         // protocol
	Extra    map[string]any // extra
}

func (p Port) CstxType() string { return "port" }

// EntityValue encodes Port as the schema-named payload.
func (p Port) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 4)
	if len(p.Extra) > 0 {
		encoded, err := json.Marshal(p.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "ip", Value: &cstxproto.EntityField_Text{Text: p.Ip}})
	fields = append(fields, &cstxproto.EntityField{Name: "port", Value: &cstxproto.EntityField_Text{Text: p.Port}})
	fields = append(fields, &cstxproto.EntityField{Name: "protocol", Value: &cstxproto.EntityField_Text{Text: p.Protocol}})
	return &cstxproto.EntityValue{NodeType: "port", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (p Port) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := p.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// PortFrom reads one payload back into Port. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func PortFrom(value *cstxproto.EntityValue) (Port, error) {
	var out Port
	if got := value.GetNodeType(); got != "port" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "port", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "ip":
			out.Ip = field.GetText()
		case "port":
			out.Port = field.GetText()
		case "protocol":
			out.Protocol = field.GetText()
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// App is the "app" node type.
type App struct {
	AppId          string         // app_id
	Url            *string        // url
	Frameworks     []string       // frameworks
	Title          *string        // title
	Midware        *string        // midware
	Status         *string        // status
	StatusCode     *int64         // status_code
	Host           *string        // host
	ContentType    *string        // content_type
	BodyLength     *int64         // body_length
	HeaderLength   *int64         // header_length
	ScreenshotId   *string        // screenshot_id
	ScreenshotPath *string        // screenshot_path
	Ip             *string        // ip
	Port           *string        // port
	Extra          map[string]any // extra
}

func (a App) CstxType() string { return "app" }

// EntityValue encodes App as the schema-named payload.
func (a App) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 16)
	fields = append(fields, &cstxproto.EntityField{Name: "app_id", Value: &cstxproto.EntityField_Text{Text: a.AppId}})
	if a.BodyLength != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "body_length", Value: &cstxproto.EntityField_Number{Number: *a.BodyLength}})
	}
	if a.ContentType != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "content_type", Value: &cstxproto.EntityField_Text{Text: *a.ContentType}})
	}
	if len(a.Extra) > 0 {
		encoded, err := json.Marshal(a.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if len(a.Frameworks) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "frameworks", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: a.Frameworks}}})
	}
	if a.HeaderLength != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "header_length", Value: &cstxproto.EntityField_Number{Number: *a.HeaderLength}})
	}
	if a.Host != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "host", Value: &cstxproto.EntityField_Text{Text: *a.Host}})
	}
	if a.Ip != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "ip", Value: &cstxproto.EntityField_Text{Text: *a.Ip}})
	}
	if a.Midware != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "midware", Value: &cstxproto.EntityField_Text{Text: *a.Midware}})
	}
	if a.Port != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "port", Value: &cstxproto.EntityField_Text{Text: *a.Port}})
	}
	if a.ScreenshotId != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "screenshot_id", Value: &cstxproto.EntityField_Text{Text: *a.ScreenshotId}})
	}
	if a.ScreenshotPath != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "screenshot_path", Value: &cstxproto.EntityField_Text{Text: *a.ScreenshotPath}})
	}
	if a.Status != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "status", Value: &cstxproto.EntityField_Text{Text: *a.Status}})
	}
	if a.StatusCode != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "status_code", Value: &cstxproto.EntityField_Number{Number: *a.StatusCode}})
	}
	if a.Title != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "title", Value: &cstxproto.EntityField_Text{Text: *a.Title}})
	}
	if a.Url != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "url", Value: &cstxproto.EntityField_Text{Text: *a.Url}})
	}
	return &cstxproto.EntityValue{NodeType: "app", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (a App) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := a.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// AppFrom reads one payload back into App. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func AppFrom(value *cstxproto.EntityValue) (App, error) {
	var out App
	if got := value.GetNodeType(); got != "app" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "app", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "app_id":
			out.AppId = field.GetText()
		case "url":
			carried := field.GetText()
			out.Url = &carried
		case "frameworks":
			out.Frameworks = field.GetList().GetValues()
		case "title":
			carried := field.GetText()
			out.Title = &carried
		case "midware":
			carried := field.GetText()
			out.Midware = &carried
		case "status":
			carried := field.GetText()
			out.Status = &carried
		case "status_code":
			carried := field.GetNumber()
			out.StatusCode = &carried
		case "host":
			carried := field.GetText()
			out.Host = &carried
		case "content_type":
			carried := field.GetText()
			out.ContentType = &carried
		case "body_length":
			carried := field.GetNumber()
			out.BodyLength = &carried
		case "header_length":
			carried := field.GetNumber()
			out.HeaderLength = &carried
		case "screenshot_id":
			carried := field.GetText()
			out.ScreenshotId = &carried
		case "screenshot_path":
			carried := field.GetText()
			out.ScreenshotPath = &carried
		case "ip":
			carried := field.GetText()
			out.Ip = &carried
		case "port":
			carried := field.GetText()
			out.Port = &carried
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Url is the "url" node type.
type Url struct {
	Scheme      string         // scheme
	Host        *string        // host
	Port        *string        // port
	Path        *string        // path
	Ip          *string        // ip
	StatusCode  *int64         // status_code
	Title       *string        // title
	BodyLength  *int64         // body_length
	ContentType *string        // content_type
	RedirectUrl *string        // redirect_url
	Frameworks  []string       // frameworks
	Url         string         // url
	Extra       map[string]any // extra
}

func (u Url) CstxType() string { return "url" }

// EntityValue encodes Url as the schema-named payload.
func (u Url) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 13)
	if u.BodyLength != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "body_length", Value: &cstxproto.EntityField_Number{Number: *u.BodyLength}})
	}
	if u.ContentType != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "content_type", Value: &cstxproto.EntityField_Text{Text: *u.ContentType}})
	}
	if len(u.Extra) > 0 {
		encoded, err := json.Marshal(u.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if len(u.Frameworks) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "frameworks", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: u.Frameworks}}})
	}
	if u.Host != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "host", Value: &cstxproto.EntityField_Text{Text: *u.Host}})
	}
	if u.Ip != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "ip", Value: &cstxproto.EntityField_Text{Text: *u.Ip}})
	}
	if u.Path != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "path", Value: &cstxproto.EntityField_Text{Text: *u.Path}})
	}
	if u.Port != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "port", Value: &cstxproto.EntityField_Text{Text: *u.Port}})
	}
	if u.RedirectUrl != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "redirect_url", Value: &cstxproto.EntityField_Text{Text: *u.RedirectUrl}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "scheme", Value: &cstxproto.EntityField_Text{Text: u.Scheme}})
	if u.StatusCode != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "status_code", Value: &cstxproto.EntityField_Number{Number: *u.StatusCode}})
	}
	if u.Title != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "title", Value: &cstxproto.EntityField_Text{Text: *u.Title}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "url", Value: &cstxproto.EntityField_Text{Text: u.Url}})
	return &cstxproto.EntityValue{NodeType: "url", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (u Url) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := u.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// UrlFrom reads one payload back into Url. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func UrlFrom(value *cstxproto.EntityValue) (Url, error) {
	var out Url
	if got := value.GetNodeType(); got != "url" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "url", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "scheme":
			out.Scheme = field.GetText()
		case "host":
			carried := field.GetText()
			out.Host = &carried
		case "port":
			carried := field.GetText()
			out.Port = &carried
		case "path":
			carried := field.GetText()
			out.Path = &carried
		case "ip":
			carried := field.GetText()
			out.Ip = &carried
		case "status_code":
			carried := field.GetNumber()
			out.StatusCode = &carried
		case "title":
			carried := field.GetText()
			out.Title = &carried
		case "body_length":
			carried := field.GetNumber()
			out.BodyLength = &carried
		case "content_type":
			carried := field.GetText()
			out.ContentType = &carried
		case "redirect_url":
			carried := field.GetText()
			out.RedirectUrl = &carried
		case "frameworks":
			out.Frameworks = field.GetList().GetValues()
		case "url":
			out.Url = field.GetText()
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Framework is the "framework" node type.
type Framework struct {
	Name    string         // name
	Part    *string        // part
	Vendor  *string        // vendor
	Product *string        // product
	Version *string        // version
	Tags    []string       // tags
	IsFocus *bool          // is_focus
	Sources []string       // sources
	Extra   map[string]any // extra
}

func (f Framework) CstxType() string { return "framework" }

// EntityValue encodes Framework as the schema-named payload.
func (f Framework) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 9)
	if len(f.Extra) > 0 {
		encoded, err := json.Marshal(f.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if f.IsFocus != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "is_focus", Value: &cstxproto.EntityField_Flag{Flag: *f.IsFocus}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "name", Value: &cstxproto.EntityField_Text{Text: f.Name}})
	if f.Part != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "part", Value: &cstxproto.EntityField_Text{Text: *f.Part}})
	}
	if f.Product != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "product", Value: &cstxproto.EntityField_Text{Text: *f.Product}})
	}
	if len(f.Sources) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "sources", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: f.Sources}}})
	}
	if len(f.Tags) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "tags", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: f.Tags}}})
	}
	if f.Vendor != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "vendor", Value: &cstxproto.EntityField_Text{Text: *f.Vendor}})
	}
	if f.Version != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "version", Value: &cstxproto.EntityField_Text{Text: *f.Version}})
	}
	return &cstxproto.EntityValue{NodeType: "framework", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (f Framework) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := f.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// FrameworkFrom reads one payload back into Framework. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func FrameworkFrom(value *cstxproto.EntityValue) (Framework, error) {
	var out Framework
	if got := value.GetNodeType(); got != "framework" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "framework", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "name":
			out.Name = field.GetText()
		case "part":
			carried := field.GetText()
			out.Part = &carried
		case "vendor":
			carried := field.GetText()
			out.Vendor = &carried
		case "product":
			carried := field.GetText()
			out.Product = &carried
		case "version":
			carried := field.GetText()
			out.Version = &carried
		case "tags":
			out.Tags = field.GetList().GetValues()
		case "is_focus":
			carried := field.GetFlag()
			out.IsFocus = &carried
		case "sources":
			out.Sources = field.GetList().GetValues()
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Vuln is the "vuln" node type.
type Vuln struct {
	Value     string         // value
	VulnId    *string        // vuln_id
	Name      *string        // name
	AssetId   *string        // asset_id
	Severity  *string        // severity
	Tags      []string       // tags
	Ip        *string        // ip
	Host      *string        // host
	Port      *string        // port
	Protocol  *string        // protocol
	Scheme    *string        // scheme
	Url       *string        // url
	Path      *string        // path
	Pocname   *string        // pocname
	Request   *string        // request
	Response  *string        // response
	Username  *string        // username
	Password  *string        // password
	Matched   *bool          // matched
	Extracted *bool          // extracted
	Extra     map[string]any // extra
}

func (v Vuln) CstxType() string { return "vuln" }

// EntityValue encodes Vuln as the schema-named payload.
func (v Vuln) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 21)
	if v.AssetId != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "asset_id", Value: &cstxproto.EntityField_Text{Text: *v.AssetId}})
	}
	if len(v.Extra) > 0 {
		encoded, err := json.Marshal(v.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if v.Extracted != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "extracted", Value: &cstxproto.EntityField_Flag{Flag: *v.Extracted}})
	}
	if v.Host != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "host", Value: &cstxproto.EntityField_Text{Text: *v.Host}})
	}
	if v.Ip != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "ip", Value: &cstxproto.EntityField_Text{Text: *v.Ip}})
	}
	if v.Matched != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "matched", Value: &cstxproto.EntityField_Flag{Flag: *v.Matched}})
	}
	if v.Name != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "name", Value: &cstxproto.EntityField_Text{Text: *v.Name}})
	}
	if v.Password != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "password", Value: &cstxproto.EntityField_Text{Text: *v.Password}})
	}
	if v.Path != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "path", Value: &cstxproto.EntityField_Text{Text: *v.Path}})
	}
	if v.Pocname != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "pocname", Value: &cstxproto.EntityField_Text{Text: *v.Pocname}})
	}
	if v.Port != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "port", Value: &cstxproto.EntityField_Text{Text: *v.Port}})
	}
	if v.Protocol != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "protocol", Value: &cstxproto.EntityField_Text{Text: *v.Protocol}})
	}
	if v.Request != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "request", Value: &cstxproto.EntityField_Text{Text: *v.Request}})
	}
	if v.Response != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "response", Value: &cstxproto.EntityField_Text{Text: *v.Response}})
	}
	if v.Scheme != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "scheme", Value: &cstxproto.EntityField_Text{Text: *v.Scheme}})
	}
	if v.Severity != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "severity", Value: &cstxproto.EntityField_Text{Text: *v.Severity}})
	}
	if len(v.Tags) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "tags", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: v.Tags}}})
	}
	if v.Url != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "url", Value: &cstxproto.EntityField_Text{Text: *v.Url}})
	}
	if v.Username != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "username", Value: &cstxproto.EntityField_Text{Text: *v.Username}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "value", Value: &cstxproto.EntityField_Text{Text: v.Value}})
	if v.VulnId != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "vuln_id", Value: &cstxproto.EntityField_Text{Text: *v.VulnId}})
	}
	return &cstxproto.EntityValue{NodeType: "vuln", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (v Vuln) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := v.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// VulnFrom reads one payload back into Vuln. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func VulnFrom(value *cstxproto.EntityValue) (Vuln, error) {
	var out Vuln
	if got := value.GetNodeType(); got != "vuln" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "vuln", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "value":
			out.Value = field.GetText()
		case "vuln_id":
			carried := field.GetText()
			out.VulnId = &carried
		case "name":
			carried := field.GetText()
			out.Name = &carried
		case "asset_id":
			carried := field.GetText()
			out.AssetId = &carried
		case "severity":
			carried := field.GetText()
			out.Severity = &carried
		case "tags":
			out.Tags = field.GetList().GetValues()
		case "ip":
			carried := field.GetText()
			out.Ip = &carried
		case "host":
			carried := field.GetText()
			out.Host = &carried
		case "port":
			carried := field.GetText()
			out.Port = &carried
		case "protocol":
			carried := field.GetText()
			out.Protocol = &carried
		case "scheme":
			carried := field.GetText()
			out.Scheme = &carried
		case "url":
			carried := field.GetText()
			out.Url = &carried
		case "path":
			carried := field.GetText()
			out.Path = &carried
		case "pocname":
			carried := field.GetText()
			out.Pocname = &carried
		case "request":
			carried := field.GetText()
			out.Request = &carried
		case "response":
			carried := field.GetText()
			out.Response = &carried
		case "username":
			carried := field.GetText()
			out.Username = &carried
		case "password":
			carried := field.GetText()
			out.Password = &carried
		case "matched":
			carried := field.GetFlag()
			out.Matched = &carried
		case "extracted":
			carried := field.GetFlag()
			out.Extracted = &carried
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// SarifVuln is the "sarif_vuln" node type.
type SarifVuln struct {
	Value         string         // value
	VulnId        *string        // vuln_id
	Title         *string        // title
	Description   *string        // description
	Source        *string        // source
	Target        *string        // target
	Tags          []string       // tags
	AssetCstxId   *string        // asset_cstx_id
	Kind          *string        // kind
	Level         *string        // level
	BaselineState *string        // baseline_state
	RuleId        *string        // rule_id
	Evidence      *string        // evidence
	Extra         map[string]any // extra
}

func (s SarifVuln) CstxType() string { return "sarif_vuln" }

// EntityValue encodes SarifVuln as the schema-named payload.
func (s SarifVuln) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 14)
	if s.AssetCstxId != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "asset_cstx_id", Value: &cstxproto.EntityField_Text{Text: *s.AssetCstxId}})
	}
	if s.BaselineState != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "baseline_state", Value: &cstxproto.EntityField_Text{Text: *s.BaselineState}})
	}
	if s.Description != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "description", Value: &cstxproto.EntityField_Text{Text: *s.Description}})
	}
	if s.Evidence != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "evidence", Value: &cstxproto.EntityField_Text{Text: *s.Evidence}})
	}
	if len(s.Extra) > 0 {
		encoded, err := json.Marshal(s.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if s.Kind != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "kind", Value: &cstxproto.EntityField_Text{Text: *s.Kind}})
	}
	if s.Level != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "level", Value: &cstxproto.EntityField_Text{Text: *s.Level}})
	}
	if s.RuleId != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "rule_id", Value: &cstxproto.EntityField_Text{Text: *s.RuleId}})
	}
	if s.Source != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "source", Value: &cstxproto.EntityField_Text{Text: *s.Source}})
	}
	if len(s.Tags) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "tags", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: s.Tags}}})
	}
	if s.Target != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "target", Value: &cstxproto.EntityField_Text{Text: *s.Target}})
	}
	if s.Title != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "title", Value: &cstxproto.EntityField_Text{Text: *s.Title}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "value", Value: &cstxproto.EntityField_Text{Text: s.Value}})
	if s.VulnId != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "vuln_id", Value: &cstxproto.EntityField_Text{Text: *s.VulnId}})
	}
	return &cstxproto.EntityValue{NodeType: "sarif_vuln", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (s SarifVuln) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := s.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// SarifVulnFrom reads one payload back into SarifVuln. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func SarifVulnFrom(value *cstxproto.EntityValue) (SarifVuln, error) {
	var out SarifVuln
	if got := value.GetNodeType(); got != "sarif_vuln" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "sarif_vuln", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "value":
			out.Value = field.GetText()
		case "vuln_id":
			carried := field.GetText()
			out.VulnId = &carried
		case "title":
			carried := field.GetText()
			out.Title = &carried
		case "description":
			carried := field.GetText()
			out.Description = &carried
		case "source":
			carried := field.GetText()
			out.Source = &carried
		case "target":
			carried := field.GetText()
			out.Target = &carried
		case "tags":
			out.Tags = field.GetList().GetValues()
		case "asset_cstx_id":
			carried := field.GetText()
			out.AssetCstxId = &carried
		case "kind":
			carried := field.GetText()
			out.Kind = &carried
		case "level":
			carried := field.GetText()
			out.Level = &carried
		case "baseline_state":
			carried := field.GetText()
			out.BaselineState = &carried
		case "rule_id":
			carried := field.GetText()
			out.RuleId = &carried
		case "evidence":
			carried := field.GetText()
			out.Evidence = &carried
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Certificate is the "certificate" node type.
type Certificate struct {
	Fingerprint string         // fingerprint
	Serial      *string        // serial
	Issuer      *string        // issuer
	Subject     *string        // subject
	NotBefore   *string        // not_before
	NotAfter    *string        // not_after
	San         []string       // san
	Host        *string        // host
	Ip          *string        // ip
	Extra       map[string]any // extra
}

func (c Certificate) CstxType() string { return "certificate" }

// EntityValue encodes Certificate as the schema-named payload.
func (c Certificate) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 10)
	if len(c.Extra) > 0 {
		encoded, err := json.Marshal(c.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "fingerprint", Value: &cstxproto.EntityField_Text{Text: c.Fingerprint}})
	if c.Host != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "host", Value: &cstxproto.EntityField_Text{Text: *c.Host}})
	}
	if c.Ip != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "ip", Value: &cstxproto.EntityField_Text{Text: *c.Ip}})
	}
	if c.Issuer != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "issuer", Value: &cstxproto.EntityField_Text{Text: *c.Issuer}})
	}
	if c.NotAfter != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "not_after", Value: &cstxproto.EntityField_Text{Text: *c.NotAfter}})
	}
	if c.NotBefore != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "not_before", Value: &cstxproto.EntityField_Text{Text: *c.NotBefore}})
	}
	if len(c.San) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "san", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: c.San}}})
	}
	if c.Serial != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "serial", Value: &cstxproto.EntityField_Text{Text: *c.Serial}})
	}
	if c.Subject != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "subject", Value: &cstxproto.EntityField_Text{Text: *c.Subject}})
	}
	return &cstxproto.EntityValue{NodeType: "certificate", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (c Certificate) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := c.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// CertificateFrom reads one payload back into Certificate. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func CertificateFrom(value *cstxproto.EntityValue) (Certificate, error) {
	var out Certificate
	if got := value.GetNodeType(); got != "certificate" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "certificate", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "fingerprint":
			out.Fingerprint = field.GetText()
		case "serial":
			carried := field.GetText()
			out.Serial = &carried
		case "issuer":
			carried := field.GetText()
			out.Issuer = &carried
		case "subject":
			carried := field.GetText()
			out.Subject = &carried
		case "not_before":
			carried := field.GetText()
			out.NotBefore = &carried
		case "not_after":
			carried := field.GetText()
			out.NotAfter = &carried
		case "san":
			out.San = field.GetList().GetValues()
		case "host":
			carried := field.GetText()
			out.Host = &carried
		case "ip":
			carried := field.GetText()
			out.Ip = &carried
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Company is the "company" node type.
type Company struct {
	Name   string         // name
	Perc   *string        // perc
	Tycid  *string        // tycid
	Icp    *string        // icp
	Parent *string        // parent
	Extra  map[string]any // extra
}

func (c Company) CstxType() string { return "company" }

// EntityValue encodes Company as the schema-named payload.
func (c Company) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 6)
	if len(c.Extra) > 0 {
		encoded, err := json.Marshal(c.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if c.Icp != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "icp", Value: &cstxproto.EntityField_Text{Text: *c.Icp}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "name", Value: &cstxproto.EntityField_Text{Text: c.Name}})
	if c.Parent != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "parent", Value: &cstxproto.EntityField_Text{Text: *c.Parent}})
	}
	if c.Perc != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "perc", Value: &cstxproto.EntityField_Text{Text: *c.Perc}})
	}
	if c.Tycid != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "tycid", Value: &cstxproto.EntityField_Text{Text: *c.Tycid}})
	}
	return &cstxproto.EntityValue{NodeType: "company", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (c Company) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := c.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// CompanyFrom reads one payload back into Company. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func CompanyFrom(value *cstxproto.EntityValue) (Company, error) {
	var out Company
	if got := value.GetNodeType(); got != "company" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "company", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "name":
			out.Name = field.GetText()
		case "perc":
			carried := field.GetText()
			out.Perc = &carried
		case "tycid":
			carried := field.GetText()
			out.Tycid = &carried
		case "icp":
			carried := field.GetText()
			out.Icp = &carried
		case "parent":
			carried := field.GetText()
			out.Parent = &carried
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Icp is the "icp" node type.
type Icp struct {
	Icp     string         // icp
	Sub     *string        // sub
	Date    *string        // date
	Company *string        // company
	Title   *string        // title
	Domain  *string        // domain
	Ip      *string        // ip
	Extra   map[string]any // extra
}

func (i Icp) CstxType() string { return "icp" }

// EntityValue encodes Icp as the schema-named payload.
func (i Icp) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 8)
	if i.Company != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "company", Value: &cstxproto.EntityField_Text{Text: *i.Company}})
	}
	if i.Date != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "date", Value: &cstxproto.EntityField_Text{Text: *i.Date}})
	}
	if i.Domain != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "domain", Value: &cstxproto.EntityField_Text{Text: *i.Domain}})
	}
	if len(i.Extra) > 0 {
		encoded, err := json.Marshal(i.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "icp", Value: &cstxproto.EntityField_Text{Text: i.Icp}})
	if i.Ip != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "ip", Value: &cstxproto.EntityField_Text{Text: *i.Ip}})
	}
	if i.Sub != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "sub", Value: &cstxproto.EntityField_Text{Text: *i.Sub}})
	}
	if i.Title != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "title", Value: &cstxproto.EntityField_Text{Text: *i.Title}})
	}
	return &cstxproto.EntityValue{NodeType: "icp", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (i Icp) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := i.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// IcpFrom reads one payload back into Icp. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func IcpFrom(value *cstxproto.EntityValue) (Icp, error) {
	var out Icp
	if got := value.GetNodeType(); got != "icp" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "icp", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "icp":
			out.Icp = field.GetText()
		case "sub":
			carried := field.GetText()
			out.Sub = &carried
		case "date":
			carried := field.GetText()
			out.Date = &carried
		case "company":
			carried := field.GetText()
			out.Company = &carried
		case "title":
			carried := field.GetText()
			out.Title = &carried
		case "domain":
			carried := field.GetText()
			out.Domain = &carried
		case "ip":
			carried := field.GetText()
			out.Ip = &carried
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Bucket is the "bucket" node type.
type Bucket struct {
	Provider    *string        // provider
	Name        *string        // name
	Region      *string        // region
	Endpoint    string         // endpoint
	Acl         *string        // acl
	ObjectCount *int64         // object_count
	KnownPaths  []string       // known_paths
	SourceUrl   *string        // source_url
	Extra       map[string]any // extra
}

func (b Bucket) CstxType() string { return "bucket" }

// EntityValue encodes Bucket as the schema-named payload.
func (b Bucket) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 9)
	if b.Acl != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "acl", Value: &cstxproto.EntityField_Text{Text: *b.Acl}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "endpoint", Value: &cstxproto.EntityField_Text{Text: b.Endpoint}})
	if len(b.Extra) > 0 {
		encoded, err := json.Marshal(b.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if len(b.KnownPaths) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "known_paths", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: b.KnownPaths}}})
	}
	if b.Name != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "name", Value: &cstxproto.EntityField_Text{Text: *b.Name}})
	}
	if b.ObjectCount != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "object_count", Value: &cstxproto.EntityField_Number{Number: *b.ObjectCount}})
	}
	if b.Provider != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "provider", Value: &cstxproto.EntityField_Text{Text: *b.Provider}})
	}
	if b.Region != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "region", Value: &cstxproto.EntityField_Text{Text: *b.Region}})
	}
	if b.SourceUrl != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "source_url", Value: &cstxproto.EntityField_Text{Text: *b.SourceUrl}})
	}
	return &cstxproto.EntityValue{NodeType: "bucket", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (b Bucket) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := b.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// BucketFrom reads one payload back into Bucket. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func BucketFrom(value *cstxproto.EntityValue) (Bucket, error) {
	var out Bucket
	if got := value.GetNodeType(); got != "bucket" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "bucket", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "provider":
			carried := field.GetText()
			out.Provider = &carried
		case "name":
			carried := field.GetText()
			out.Name = &carried
		case "region":
			carried := field.GetText()
			out.Region = &carried
		case "endpoint":
			out.Endpoint = field.GetText()
		case "acl":
			carried := field.GetText()
			out.Acl = &carried
		case "object_count":
			carried := field.GetNumber()
			out.ObjectCount = &carried
		case "known_paths":
			out.KnownPaths = field.GetList().GetValues()
		case "source_url":
			carried := field.GetText()
			out.SourceUrl = &carried
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Endpoint is the "endpoint" node type.
type Endpoint struct {
	Url         string         // url
	Method      *string        // method
	Path        *string        // path
	ContentType *string        // content_type
	StatusCode  *int64         // status_code
	Source      *string        // source
	SourceUrl   *string        // source_url
	Parameters  []string       // parameters
	Tags        []string       // tags
	Extra       map[string]any // extra
}

func (e Endpoint) CstxType() string { return "endpoint" }

// EntityValue encodes Endpoint as the schema-named payload.
func (e Endpoint) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 10)
	if e.ContentType != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "content_type", Value: &cstxproto.EntityField_Text{Text: *e.ContentType}})
	}
	if len(e.Extra) > 0 {
		encoded, err := json.Marshal(e.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if e.Method != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "method", Value: &cstxproto.EntityField_Text{Text: *e.Method}})
	}
	if len(e.Parameters) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "parameters", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: e.Parameters}}})
	}
	if e.Path != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "path", Value: &cstxproto.EntityField_Text{Text: *e.Path}})
	}
	if e.Source != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "source", Value: &cstxproto.EntityField_Text{Text: *e.Source}})
	}
	if e.SourceUrl != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "source_url", Value: &cstxproto.EntityField_Text{Text: *e.SourceUrl}})
	}
	if e.StatusCode != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "status_code", Value: &cstxproto.EntityField_Number{Number: *e.StatusCode}})
	}
	if len(e.Tags) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "tags", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: e.Tags}}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "url", Value: &cstxproto.EntityField_Text{Text: e.Url}})
	return &cstxproto.EntityValue{NodeType: "endpoint", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (e Endpoint) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := e.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// EndpointFrom reads one payload back into Endpoint. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func EndpointFrom(value *cstxproto.EntityValue) (Endpoint, error) {
	var out Endpoint
	if got := value.GetNodeType(); got != "endpoint" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "endpoint", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "url":
			out.Url = field.GetText()
		case "method":
			carried := field.GetText()
			out.Method = &carried
		case "path":
			carried := field.GetText()
			out.Path = &carried
		case "content_type":
			carried := field.GetText()
			out.ContentType = &carried
		case "status_code":
			carried := field.GetNumber()
			out.StatusCode = &carried
		case "source":
			carried := field.GetText()
			out.Source = &carried
		case "source_url":
			carried := field.GetText()
			out.SourceUrl = &carried
		case "parameters":
			out.Parameters = field.GetList().GetValues()
		case "tags":
			out.Tags = field.GetList().GetValues()
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Host is the "host" node type.
type Host struct {
	Hostname   string         // hostname
	LocalIps   []string       // local_ips
	GatewayIps []string       // gateway_ips
	DnsServers []string       // dns_servers
	DomainName *string        // domain_name
	DomainRole *string        // domain_role
	Extra      map[string]any // extra
}

func (h Host) CstxType() string { return "host" }

// EntityValue encodes Host as the schema-named payload.
func (h Host) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 7)
	if len(h.DnsServers) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "dns_servers", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: h.DnsServers}}})
	}
	if h.DomainName != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "domain_name", Value: &cstxproto.EntityField_Text{Text: *h.DomainName}})
	}
	if h.DomainRole != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "domain_role", Value: &cstxproto.EntityField_Text{Text: *h.DomainRole}})
	}
	if len(h.Extra) > 0 {
		encoded, err := json.Marshal(h.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if len(h.GatewayIps) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "gateway_ips", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: h.GatewayIps}}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "hostname", Value: &cstxproto.EntityField_Text{Text: h.Hostname}})
	if len(h.LocalIps) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "local_ips", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: h.LocalIps}}})
	}
	return &cstxproto.EntityValue{NodeType: "host", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (h Host) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := h.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// HostFrom reads one payload back into Host. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func HostFrom(value *cstxproto.EntityValue) (Host, error) {
	var out Host
	if got := value.GetNodeType(); got != "host" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "host", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "hostname":
			out.Hostname = field.GetText()
		case "local_ips":
			out.LocalIps = field.GetList().GetValues()
		case "gateway_ips":
			out.GatewayIps = field.GetList().GetValues()
		case "dns_servers":
			out.DnsServers = field.GetList().GetValues()
		case "domain_name":
			carried := field.GetText()
			out.DomainName = &carried
		case "domain_role":
			carried := field.GetText()
			out.DomainRole = &carried
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Repository is the "repository" node type.
type Repository struct {
	Provider     *string        // provider
	Name         *string        // name
	Url          string         // url
	Owner        *string        // owner
	Description  *string        // description
	Stars        *int64         // stars
	IsFork       *bool          // is_fork
	MatchedDorks []string       // matched_dorks
	Extra        map[string]any // extra
}

func (r Repository) CstxType() string { return "repository" }

// EntityValue encodes Repository as the schema-named payload.
func (r Repository) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 9)
	if r.Description != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "description", Value: &cstxproto.EntityField_Text{Text: *r.Description}})
	}
	if len(r.Extra) > 0 {
		encoded, err := json.Marshal(r.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if r.IsFork != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "is_fork", Value: &cstxproto.EntityField_Flag{Flag: *r.IsFork}})
	}
	if len(r.MatchedDorks) > 0 {
		fields = append(fields, &cstxproto.EntityField{Name: "matched_dorks", Value: &cstxproto.EntityField_List{List: &cstxproto.StringList{Values: r.MatchedDorks}}})
	}
	if r.Name != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "name", Value: &cstxproto.EntityField_Text{Text: *r.Name}})
	}
	if r.Owner != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "owner", Value: &cstxproto.EntityField_Text{Text: *r.Owner}})
	}
	if r.Provider != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "provider", Value: &cstxproto.EntityField_Text{Text: *r.Provider}})
	}
	if r.Stars != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "stars", Value: &cstxproto.EntityField_Number{Number: *r.Stars}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "url", Value: &cstxproto.EntityField_Text{Text: r.Url}})
	return &cstxproto.EntityValue{NodeType: "repository", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (r Repository) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := r.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// RepositoryFrom reads one payload back into Repository. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func RepositoryFrom(value *cstxproto.EntityValue) (Repository, error) {
	var out Repository
	if got := value.GetNodeType(); got != "repository" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "repository", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "provider":
			carried := field.GetText()
			out.Provider = &carried
		case "name":
			carried := field.GetText()
			out.Name = &carried
		case "url":
			out.Url = field.GetText()
		case "owner":
			carried := field.GetText()
			out.Owner = &carried
		case "description":
			carried := field.GetText()
			out.Description = &carried
		case "stars":
			carried := field.GetNumber()
			out.Stars = &carried
		case "is_fork":
			carried := field.GetFlag()
			out.IsFork = &carried
		case "matched_dorks":
			out.MatchedDorks = field.GetList().GetValues()
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Secret is the "secret" node type.
type Secret struct {
	Kind        *string        // kind
	Detector    *string        // detector
	Redacted    *string        // redacted
	Fingerprint string         // fingerprint
	Source      *string        // source
	SourceUrl   *string        // source_url
	FilePath    *string        // file_path
	Line        *int64         // line
	Commit      *string        // commit
	Verified    *bool          // verified
	Severity    *string        // severity
	Extra       map[string]any // extra
}

func (s Secret) CstxType() string { return "secret" }

// EntityValue encodes Secret as the schema-named payload.
func (s Secret) EntityValue() (*cstxproto.EntityValue, error) {
	fields := make([]*cstxproto.EntityField, 0, 12)
	if s.Commit != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "commit", Value: &cstxproto.EntityField_Text{Text: *s.Commit}})
	}
	if s.Detector != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "detector", Value: &cstxproto.EntityField_Text{Text: *s.Detector}})
	}
	if len(s.Extra) > 0 {
		encoded, err := json.Marshal(s.Extra)
		if err != nil {
			return nil, fmt.Errorf("cstx: field %q is not encodable as JSON: %w", "extra", err)
		}
		fields = append(fields, &cstxproto.EntityField{Name: "extra", Value: &cstxproto.EntityField_Text{Text: string(encoded)}})
	}
	if s.FilePath != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "file_path", Value: &cstxproto.EntityField_Text{Text: *s.FilePath}})
	}
	fields = append(fields, &cstxproto.EntityField{Name: "fingerprint", Value: &cstxproto.EntityField_Text{Text: s.Fingerprint}})
	if s.Kind != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "kind", Value: &cstxproto.EntityField_Text{Text: *s.Kind}})
	}
	if s.Line != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "line", Value: &cstxproto.EntityField_Number{Number: *s.Line}})
	}
	if s.Redacted != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "redacted", Value: &cstxproto.EntityField_Text{Text: *s.Redacted}})
	}
	if s.Severity != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "severity", Value: &cstxproto.EntityField_Text{Text: *s.Severity}})
	}
	if s.Source != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "source", Value: &cstxproto.EntityField_Text{Text: *s.Source}})
	}
	if s.SourceUrl != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "source_url", Value: &cstxproto.EntityField_Text{Text: *s.SourceUrl}})
	}
	if s.Verified != nil {
		fields = append(fields, &cstxproto.EntityField{Name: "verified", Value: &cstxproto.EntityField_Flag{Flag: *s.Verified}})
	}
	return &cstxproto.EntityValue{NodeType: "secret", Fields: fields}, nil
}

// Node wraps the payload as a graph node. The id is left unset: identity is
// the schema document's rule and the runtime derives it from the payload.
func (s Secret) Node(sources ...string) (*cstxproto.Node, error) {
	value, err := s.EntityValue()
	if err != nil {
		return nil, err
	}
	return &cstxproto.Node{Value: value, Sources: sources}, nil
}

// SecretFrom reads one payload back into Secret. Names the schema does not
// declare are left alone: a producer may send more than this build knows.
func SecretFrom(value *cstxproto.EntityValue) (Secret, error) {
	var out Secret
	if got := value.GetNodeType(); got != "secret" {
		return out, fmt.Errorf("cstx: expected node type %q, got %q", "secret", got)
	}
	for _, field := range value.GetFields() {
		switch field.GetName() {
		case "kind":
			carried := field.GetText()
			out.Kind = &carried
		case "detector":
			carried := field.GetText()
			out.Detector = &carried
		case "redacted":
			carried := field.GetText()
			out.Redacted = &carried
		case "fingerprint":
			out.Fingerprint = field.GetText()
		case "source":
			carried := field.GetText()
			out.Source = &carried
		case "source_url":
			carried := field.GetText()
			out.SourceUrl = &carried
		case "file_path":
			carried := field.GetText()
			out.FilePath = &carried
		case "line":
			carried := field.GetNumber()
			out.Line = &carried
		case "commit":
			carried := field.GetText()
			out.Commit = &carried
		case "verified":
			carried := field.GetFlag()
			out.Verified = &carried
		case "severity":
			carried := field.GetText()
			out.Severity = &carried
		case "extra":
			if raw := field.GetText(); raw != "" {
				if err := json.Unmarshal([]byte(raw), &out.Extra); err != nil {
					return out, fmt.Errorf("cstx: field %q is not a JSON document: %w", "extra", err)
				}
			}
		}
	}
	return out, nil
}

// Decode reads one payload back into the generated type for its node type.
func Decode(value *cstxproto.EntityValue) (Node, error) {
	switch value.GetNodeType() {
	case "domain":
		decoded, err := DomainFrom(value)
		return decoded, err
	case "subdomain":
		decoded, err := SubdomainFrom(value)
		return decoded, err
	case "ip":
		decoded, err := IpFrom(value)
		return decoded, err
	case "cidr":
		decoded, err := CidrFrom(value)
		return decoded, err
	case "port":
		decoded, err := PortFrom(value)
		return decoded, err
	case "app":
		decoded, err := AppFrom(value)
		return decoded, err
	case "url":
		decoded, err := UrlFrom(value)
		return decoded, err
	case "framework":
		decoded, err := FrameworkFrom(value)
		return decoded, err
	case "vuln":
		decoded, err := VulnFrom(value)
		return decoded, err
	case "sarif_vuln":
		decoded, err := SarifVulnFrom(value)
		return decoded, err
	case "certificate":
		decoded, err := CertificateFrom(value)
		return decoded, err
	case "company":
		decoded, err := CompanyFrom(value)
		return decoded, err
	case "icp":
		decoded, err := IcpFrom(value)
		return decoded, err
	case "bucket":
		decoded, err := BucketFrom(value)
		return decoded, err
	case "endpoint":
		decoded, err := EndpointFrom(value)
		return decoded, err
	case "host":
		decoded, err := HostFrom(value)
		return decoded, err
	case "repository":
		decoded, err := RepositoryFrom(value)
		return decoded, err
	case "secret":
		decoded, err := SecretFrom(value)
		return decoded, err
	default:
		return nil, fmt.Errorf("cstx: no generated type for node type %q", value.GetNodeType())
	}
}

const (
	RelVuln         = "vuln"
	RelResolve      = "resolve"
	RelOpen         = "open"
	RelHasSubdomain = "has-subdomain"
	RelContain      = "contain"
	RelHosts        = "hosts"
	RelUses         = "uses"
	RelRefers       = "refers"
	RelSecuredBy    = "secured_by"
	RelExploit      = "exploit"
	RelAffect       = "affect"
	RelInvest       = "invest"
	RelOwn          = "own"
	RelFiledFor     = "filed-for"
)

var RelationTypes = []string{
	RelVuln,
	RelResolve,
	RelOpen,
	RelHasSubdomain,
	RelContain,
	RelHosts,
	RelUses,
	RelRefers,
	RelSecuredBy,
	RelExploit,
	RelAffect,
	RelInvest,
	RelOwn,
	RelFiledFor,
}
