// Re-export from WASM module — the actual wasm bindings are generated by wasm-pack.
// This file provides the TypeScript-friendly wrapper with proper typing.

import type * as wasm from '../wasm/cstx_wasm';

export interface IngestResult {
  records_parsed: number;
  new_nodes: number;
  updated_nodes: number;
  new_edges: number;
  node_count: number;
  edge_count: number;
}

export interface BatchResult {
  new_nodes: number;
  updated_nodes: number;
  count: number;
}

let wasmModule: typeof wasm | null = null;

async function getWasm(): Promise<typeof wasm> {
  if (!wasmModule) {
    wasmModule = await import('../wasm/cstx_wasm');
  }
  return wasmModule;
}

export class CSTXGraph {
  private inner: wasm.CSTXGraph;

  private constructor(inner: wasm.CSTXGraph) {
    this.inner = inner;
  }

  static async create(): Promise<CSTXGraph> {
    const w = await getWasm();
    return new CSTXGraph(new w.CSTXGraph());
  }

  loadAllPlugins(): number {
    return this.inner.loadAllPlugins();
  }

  loadPlugin(name: string): void {
    this.inner.loadPlugin(name);
  }

  registerSchema(nodeType: string, jsonSchema: string, valueField?: string): void {
    this.inner.registerSchema(nodeType, jsonSchema, valueField);
  }

  addNode(nodeType: string, cstxId: string, payload: object, sources: string[], flags = 0): void {
    this.inner.addNode(nodeType, cstxId, JSON.stringify(payload), JSON.stringify(sources), BigInt(flags));
  }

  addEdge(sourceId: string, targetId: string, relation: string, dataSource: string): void {
    this.inner.addEdge(sourceId, targetId, relation, dataSource);
  }

  addNodesBatch(nodes: object[]): BatchResult {
    const json = this.inner.addNodesBatch(JSON.stringify(nodes));
    return JSON.parse(json);
  }

  addEdgesBatch(edges: object[]): number {
    return this.inner.addEdgesBatch(JSON.stringify(edges));
  }

  ingestNative(plugin: string, artifact: string, data: Uint8Array): IngestResult {
    const json = this.inner.ingestNative(plugin, artifact, data);
    return JSON.parse(json);
  }

  hasNativeArtifact(artifact: string): boolean {
    return this.inner.hasNativeArtifact(artifact);
  }

  ingestJsonl(nodeType: string, data: Uint8Array, idExpr: string, dataSource: string): IngestResult {
    const json = this.inner.ingestJsonl(nodeType, data, idExpr, dataSource);
    return JSON.parse(json);
  }

  containsNode(nodeId: string): boolean {
    return this.inner.containsNode(nodeId);
  }

  nodeCount(): number {
    return this.inner.nodeCount();
  }

  edgeCount(): number {
    return this.inner.edgeCount();
  }

  nodeTypes(): string[] {
    return JSON.parse(this.inner.nodeTypes());
  }

  nodes(typeFilter?: string): object[] {
    return JSON.parse(this.inner.nodesJson(typeFilter));
  }

  edges(relation?: string): object[] {
    return JSON.parse(this.inner.edgesJson(relation));
  }

  neighbors(nodeId: string): object[] {
    return JSON.parse(this.inner.neighborsJson(nodeId));
  }

  nodePayload(nodeId: string): object | null {
    const s = this.inner.nodePayload(nodeId);
    return s ? JSON.parse(s) : null;
  }

  stats(): { nodes: Record<string, number>; edges: Record<string, number> } {
    return JSON.parse(this.inner.stats());
  }

  toJSON(): object {
    return JSON.parse(this.inner.toJson());
  }

  version(): string {
    return this.inner.version();
  }

  supportedArtifacts(): string[] {
    return JSON.parse(this.inner.supportedArtifacts());
  }

  free(): void {
    this.inner.free();
  }
}

export async function cstxTransform(sourceType: string, data: Uint8Array): Promise<object[]> {
  const w = await getWasm();
  const json = w.cstxTransform(sourceType, data);
  return JSON.parse(json);
}
